export type Country = { name: string; iso2: string; dialCode: string };

export const COUNTRIES: Country[] = [
  { name: "United Arab Emirates", iso2: "AE", dialCode: "971" },
  { name: "Azerbaijan", iso2: "AZ", dialCode: "994" },
  { name: "Turkey", iso2: "TR", dialCode: "90" },
  { name: "Qatar", iso2: "QA", dialCode: "974" },
  { name: "Saudi Arabia", iso2: "SA", dialCode: "966" },
  { name: "Oman", iso2: "OM", dialCode: "968" },
  { name: "Bahrain", iso2: "BH", dialCode: "973" },
  { name: "Kuwait", iso2: "KW", dialCode: "965" },
  { name: "Iran", iso2: "IR", dialCode: "98" },
  { name: "Iraq", iso2: "IQ", dialCode: "964" },
  { name: "Jordan", iso2: "JO", dialCode: "962" },
  { name: "Lebanon", iso2: "LB", dialCode: "961" },
  { name: "Egypt", iso2: "EG", dialCode: "20" },
  { name: "United States", iso2: "US", dialCode: "1" },
  { name: "Canada", iso2: "CA", dialCode: "1" },
  { name: "Mexico", iso2: "MX", dialCode: "52" },
  { name: "United Kingdom", iso2: "GB", dialCode: "44" },
  { name: "Germany", iso2: "DE", dialCode: "49" },
  { name: "France", iso2: "FR", dialCode: "33" },
  { name: "Spain", iso2: "ES", dialCode: "34" },
  { name: "Italy", iso2: "IT", dialCode: "39" },
  { name: "Netherlands", iso2: "NL", dialCode: "31" },
  { name: "Belgium", iso2: "BE", dialCode: "32" },
  { name: "Switzerland", iso2: "CH", dialCode: "41" },
  { name: "Austria", iso2: "AT", dialCode: "43" },
  { name: "Sweden", iso2: "SE", dialCode: "46" },
  { name: "Norway", iso2: "NO", dialCode: "47" },
  { name: "Denmark", iso2: "DK", dialCode: "45" },
  { name: "Finland", iso2: "FI", dialCode: "358" },
  { name: "Poland", iso2: "PL", dialCode: "48" },
  { name: "Czechia", iso2: "CZ", dialCode: "420" },
  { name: "Portugal", iso2: "PT", dialCode: "351" },
  { name: "Greece", iso2: "GR", dialCode: "30" },
  { name: "Russia", iso2: "RU", dialCode: "7" },
  { name: "Ukraine", iso2: "UA", dialCode: "380" },
  { name: "Georgia", iso2: "GE", dialCode: "995" },
  { name: "Armenia", iso2: "AM", dialCode: "374" },
  { name: "Kazakhstan", iso2: "KZ", dialCode: "7" },
  { name: "Uzbekistan", iso2: "UZ", dialCode: "998" },
  { name: "India", iso2: "IN", dialCode: "91" },
  { name: "Pakistan", iso2: "PK", dialCode: "92" },
  { name: "Bangladesh", iso2: "BD", dialCode: "880" },
  { name: "China", iso2: "CN", dialCode: "86" },
  { name: "Hong Kong", iso2: "HK", dialCode: "852" },
  { name: "Macau", iso2: "MO", dialCode: "853" },
  { name: "Taiwan", iso2: "TW", dialCode: "886" },
  { name: "Japan", iso2: "JP", dialCode: "81" },
  { name: "South Korea", iso2: "KR", dialCode: "82" },
  { name: "Singapore", iso2: "SG", dialCode: "65" },
  { name: "Malaysia", iso2: "MY", dialCode: "60" },
  { name: "Indonesia", iso2: "ID", dialCode: "62" },
  { name: "Philippines", iso2: "PH", dialCode: "63" },
  { name: "Thailand", iso2: "TH", dialCode: "66" },
  { name: "Vietnam", iso2: "VN", dialCode: "84" },
  { name: "Australia", iso2: "AU", dialCode: "61" },
  { name: "New Zealand", iso2: "NZ", dialCode: "64" },
  { name: "Brazil", iso2: "BR", dialCode: "55" },
  { name: "Argentina", iso2: "AR", dialCode: "54" },
  { name: "Chile", iso2: "CL", dialCode: "56" },
  { name: "Peru", iso2: "PE", dialCode: "51" },
  { name: "Colombia", iso2: "CO", dialCode: "57" },
  { name: "South Africa", iso2: "ZA", dialCode: "27" },
  { name: "Nigeria", iso2: "NG", dialCode: "234" },
  { name: "Kenya", iso2: "KE", dialCode: "254" },
  { name: "Ghana", iso2: "GH", dialCode: "233" },
  { name: "Ethiopia", iso2: "ET", dialCode: "251" },
  { name: "Morocco", iso2: "MA", dialCode: "212" },
  { name: "Algeria", iso2: "DZ", dialCode: "213" },
  { name: "Tunisia", iso2: "TN", dialCode: "216" },
];

export function iso2ToFlag(iso2: string) {
  if (!iso2) return "🏳️";
  const codePoints = iso2
    .toUpperCase()
    .split("")
    .map((c) => 127397 + c.charCodeAt(0));
  return String.fromCodePoint(...codePoints);
}
