import "@/assets/styles/globals.css";
import "antd/dist/reset.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { ConfigProvider, Layout } from "antd";
import { Content, Footer, Header } from "antd/es/layout/layout";
import MainHeader from "@/components/Layout/Header";
import { MainFooter } from "@/components/Layout/Footer";
import { Lato } from "next/font/google";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"], 
  variable: "--font-lato",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lato.className}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "#19273d",
              // colorBgBase: "#fff",
              // colorBgContainer: "#fff",
            },
          }}
        >
          <Layout>
            <Header
              style={{
                position: "sticky",
                top: 0,
                zIndex: 1,
                padding: 0,
                height: "auto",
                lineHeight: "normal",
              }}
            >
              <MainHeader />
            </Header>
            <Content>{children}</Content>

            <MainFooter />

          </Layout>
        </ConfigProvider>
      </body>
    </html>
  );
}
