// app/layout.tsx
import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Geist, Geist_Mono } from "next/font/google";
import { Lato } from "next/font/google";

import { Layout } from "antd";
import { Content, Header } from "antd/es/layout/layout";
import NextTopLoader from "nextjs-toploader";
import MainHeader from "@/components/Layout/Header";
import { MainFooter } from "@/components/Layout/Footer";
import ClientAntdProvider from "@/components/ClientAntdProvider";

import "../../src/assets/styles/globals.scss";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
  variable: "--font-lato",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lato.className}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Dilə görə RTL/LTR və mövzu idarəsi client tərəfdə */}
        <ClientAntdProvider>
          <Layout>
            <Header
              style={{
                position: "sticky",
                top: 0,
                zIndex: 999,
                padding: 0,
                height: "auto",
                lineHeight: "normal",
              }}
            >
              <MainHeader />
            </Header>

            <Content>
              <AntdRegistry>
                <NextTopLoader showSpinner={false} height={3} />
                <Providers>{children}</Providers>
              </AntdRegistry>
            </Content>

            <MainFooter />
          </Layout>
        </ClientAntdProvider>
      </body>
    </html>
  );
}
